config/routes.rb
# Rails.application.routes.draw do
#
#   get 'questions/index'
#
#
#
#   root to: 'questions#index'
#
#   resources :questions  do
#     resources :answers
#   end
#
#   devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end


 Rails.application.routes.draw do
  resources :questions, :has_many => :answers
  root to: 'questions#index'
  resources :questions  do
      resources :answers
    end
  devise_for :users
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :body, presence: true, length: { minimum: 50 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  attr_accessor :answers_attributes
  has_many :answers, dependent: :destroy
  belongs_to :user
  accepts_nested_attributes_for :answers
  validates :headline, presence: true , length: { minimum: 20 }
  validates :body, presence: true, length: { minimum: 50 }
  validates_associated :answers
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  validates :username, presence: :true, uniqueness: {case_sensitive: false}

  def login
    @login || self.username || self.email
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_question

  def index
    @question = find_question
    @answers = @question.answers
    # @answers = @question.answers
    # @user = User.find(@question.user_id)
  end

  def show
    @answer = Answer.find(params[:id])
    @user = User.find(@question.user_id)
  end

  def new
    @answer = Answer.new(:question_id => @question.id)
  end

  def create
    @question = find_question
    # @answer = @question.answers.build(answer_params)
    @answer = Answer.new(answer_params)
    @answer.user_id = current_user.id

    if @answer.save
      flash[:notice] = "You have sucessfully created the answer."
      redirect_to @question
      # redirect_to(answers_path(@answer, :question_id => @question.id))
    else
      flash[:alert] = "Failed to save the answer."
      @errors = @answer.errors.full_messages
      render :action => '_new'
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update_attributes(answer_params)
      flash[:notice] = "You have sucessfully updated the answer."
      redirect_to(answer_path(@answer, :question_id => @question.id))
    else
      render :edit
    end
  end

  def delete
    @answer = Asnwer.find(params[:id])
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    flash[:notice] = "Answer was destroyed"
    redirect_to(answers_path)
  end

  private

   def answer_params
     params.require(:answer).permit(:body, :user_id, :question_id)
   end

   def find_question
     params.each do |name, value|
       # if name=~ /(.+)_id$/
       if name == 'question_id'
         # return $1.classify.constantize.find(value)
         return @question = Question.find(value.to_i)
       end
     end
     nil
   end

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_pemitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_pemitted_parameters
    added_attrs = %i[username email password passowrd_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, except: [:index, :new, :create]

  def index
    @questions = Question.all.order("id DESC")
  end

  def show
    @question = Question.find(params[:id])
    @user = User.find(@question.user_id)
    @answers = @question.answers
    @answer = Answer.new
  end

  def new
    @question = Question.new
    @question.answers.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      flash[:notice] = "You have successfully posted your question"
      redirect_to  @question

    else
      @errors = @question.errors.full_messages
      render action: :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
     @question = Question.find(params[:id])
     @question.update(question_params)
     @answer = @question.answers.new(question_params)
     @question.answers.first.user_id = current_user.id
   # binding.pry
   if @question.save
     flash[:notice] = "You have sucessfully posted your answer"
     redirect_to @question
   else
      redirect_to edit_question_answer_path(@answer), flash: { danger: @question.errors.full_messages.join(",")}
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:headline, :body, :user_id, :answer, answers_attributes:[:body, :user_id, :question_id])
  end

end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :email)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answers.html.erb
<div class='answers container'>


<div id="answers">
  <% for answer in @answers %>
  <div class="answer">
    <%=simple_format answer.body %>
    </div>
    <% end %>
</div>
</div>

app/views/answers/_new.html.erb
<h4> Your Answer </h4>


<%= form_for [@question, Answer.new] do |form| %>

     <div class="form-group">
        <%=form.text_area :body, placeholder: "Add your answer", rows:10, class:"form-control" %><br>

         <%=form.hidden_field :user_id, value: current_user.id, class:'d-none' %>
         <%=form.hidden_field :question_id, value: @question.id %>
      </div>

    <div>
       <%=form.submit 'Post Your Answer', class: 'btn-primary' %>
   </div>
<% end %>

app/views/answers/index.html.erb
  <div class="col-md-8 question-details">
    <div class="question-wrapper">
      <h4 class="question-title"><%=@question.headline %></h4>
        <div class="username"><%= @user.username %></div>
        <div class="question-body"><%= @question.body %></div>
    </div>
  </div>

  <div class="col-md-8 answers-details">
    <% if @answers.length === 0 %>
        <div class="answers-wrapper">
            <h4>There are no answers yet</h4>
        </div>
    <% else %>
      <div class="answers-wrapper">
        <h4>There are <%= @answers.length %> Answers </h4>

        <% @question.answers.order(:created_at).each do |answer|%>
          <% @question_user = answer.user %>
          <div class="username"><%= @question_user.username %></div>
          <div class="answer-body"><%= answer.body %></div>
        <% end %>
      </div>
    <% end %>
 </div>


    <h4> Your Answer </h4>
    <%= render '/answers/new'%>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  
    <%= javascript_include_tag "vendor/modernizr" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">RescueMission</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  
  <%- if Rails.env.development? || Rails.env.test? -%> 
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>
  
  <%= yield :extra_footer %>
</body>
</html>

app/views/questions/index.html.erb
<% if user_signed_in? %>
   <a href="<%= destroy_user_session_path%>" data-method="delete">
     <i class="fa fa-user"></i>
   </a>
<% else %>
   <a href="<%= new_user_session_path %>">
     <i class="fa fa-sign-in"></i>
   </a>
<% end %>
<table>
  <tr>
    <th>Top Questions</th>
  </tr>
  <%=link_to "New question", new_question_path, class:"ask-question" %>

  <% @questions.each do |question| %>
  <tr>
    <td>
      <% date_time = question.created_at %>
      <%=date_time.strftime("Posted on %B %d %Y") %><br>
      <%=link_to question.headline, question_path(question), class: 'view-question' %>
    </td>
  </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<h2>Ask a question</h2>


<%= form_with scope: :question, url: questions_path, local: true do |form| %>

<% if @errors %>
<ul>
  <% @errors.each do |error| %>
  <li><%= error %></li>
  <% end %>
  </ul>
<% end %>


 <p>
   <%=form.label :headline %><br>
   <%=form.text_field :headline %>
 </p>
 <p>
   <%=form.label :body %><br>
   <%=form.text_area :body %>
 </p>
 <p>
   <%=form.hidden_field :user_id, value: current_user.id, class:'d-none' %>
 </p>
 <p>
   <%= form.submit 'Post Your Question', class: 'btn-primary' %>
 </p>
 <% end %>

<% link_to 'Back', questions_path %>

app/views/questions/show.html.erb
  <div class="col-md-8 question-details">
    <div class="question-wrapper">
      <h4 class="question-title"><%=@question.headline %></h4>
        <div class="username"><%= @user.username %></div>
        <div class="question-body"><%= @question.body %></div>
    </div>
  </div>

  <div class="col-md-8 answers-details">
    <% if @answers.length > 0 %>

      <div class="answers-wrapper">
        <h4>There are <%= @answers.length %> Answers </h4>
        <%= render 'answers/answers' %>

    <% else %>

      <div class="answers-wrapper">
        <h4>There are no answers yet</h4>
      </div>

   <% end %>
 </div>

      <%= render '/answers/new'%>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>